/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Desk({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/mesh/Desk/Desk.gltf');
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[-5, 0, 5]}
      scale={[0.8, 0.8, 0.8]}
    >
      <mesh
        geometry={nodes.Reference.geometry}
        material={materials.M_UE4Man_Body}
      />
      <mesh geometry={nodes.Wall01.geometry} material={materials.Room} />
      <mesh geometry={nodes.Ground.geometry} material={materials.Room} />
      <mesh geometry={nodes.Wall02.geometry} material={materials.Room} />
      <mesh geometry={nodes.Latte.geometry} material={materials.Room} />
      <mesh geometry={nodes.PorteCasque.geometry} material={materials.Room} />
      <mesh geometry={nodes.Pouf.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cardboard.geometry} material={materials.Room} />
      <mesh geometry={nodes.PC.geometry} material={materials.Room} />
      <mesh geometry={nodes.Tableau.geometry} material={materials.Room} />
      <mesh geometry={nodes.Etagere.geometry} material={materials.Room} />
      <mesh geometry={nodes.Tapis.geometry} material={materials.Room} />
      <mesh geometry={nodes.Tasse.geometry} material={materials.Room} />
      <mesh geometry={nodes.Glass.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cochon.geometry} material={materials.Room} />
      <mesh geometry={nodes.Plane003.geometry} material={materials.Focus} />
      <mesh
        geometry={nodes.Passeport.geometry}
        material={materials.Focus}
        position={[0.01, 0, 0]}
      />
      <mesh geometry={nodes.Closet.geometry} material={materials.Room} />
      <mesh geometry={nodes.Armoire029.geometry} material={materials.Room} />
      <mesh geometry={nodes.Armoire030.geometry} material={materials.Room} />
      <mesh geometry={nodes.Armoire041.geometry} material={materials.Room} />
      <mesh geometry={nodes.Armoire042.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder022.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder024.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder025.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder058.geometry} material={materials.Room} />
      <mesh geometry={nodes.Sofa_back.geometry} material={materials.Room} />
      <mesh geometry={nodes.Side.geometry} material={materials.Room} />
      <mesh geometry={nodes.Base002.geometry} material={materials.Room} />
      <mesh geometry={nodes.Coussin1.geometry} material={materials.Room} />
      <mesh geometry={nodes.Coussin2.geometry} material={materials.Room} />
      <mesh geometry={nodes.Clavier.geometry} material={materials.Room}>
        <mesh
          geometry={nodes.Clavier_decals.geometry}
          material={materials['.Custom_002_Clavier']}
        />
      </mesh>
      <mesh
        geometry={nodes.Controller_decals1.geometry}
        material={materials['.MyDecals_003']}
      />
      <mesh
        geometry={nodes.Controller_decals2.geometry}
        material={materials['.MyDecals_003']}
      />
      <mesh
        geometry={nodes.Controller_decals3.geometry}
        material={materials['.MyDecals_003']}
      />
      <mesh geometry={nodes.Controller.geometry} material={materials.Room} />
      <mesh geometry={nodes.Macup.geometry} material={materials.Room} />
      <mesh geometry={nodes.MacDown.geometry} material={materials.Room} />
      <mesh geometry={nodes.BaseSupport.geometry} material={materials.Room} />
      <mesh geometry={nodes.SecondSupport.geometry} material={materials.Room} />
      <mesh
        geometry={nodes.BaseSupport001.geometry}
        material={materials.Room}
        position={[2.93, 1.82, -2.3]}
      />
      <mesh geometry={nodes.Base1.geometry} material={materials.Room} />
      <mesh geometry={nodes.Boule1.geometry} material={materials.Room} />
      <mesh geometry={nodes.Lamp1.geometry} material={materials.Room} />
      <mesh geometry={nodes.Base2.geometry} material={materials.Room} />
      <mesh geometry={nodes.Boule2.geometry} material={materials.Room} />
      <mesh geometry={nodes.Lamp2.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre001.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre002.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre003.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre004.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre005.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre006.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre007.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre008.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre009.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre010.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre011.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre012.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre013.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre014.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre015.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre016.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre017.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre018.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre019.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre020.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre021.geometry} material={materials.Room} />
      <mesh geometry={nodes.Livre022.geometry} material={materials.Room} />
      <mesh geometry={nodes.Base.geometry} material={materials.Room} />
      <mesh geometry={nodes.Feuille1.geometry} material={materials.Room} />
      <mesh
        geometry={nodes.Feuille2.geometry}
        material={materials.Room_Transparent}
      />
      <mesh
        geometry={nodes.Feuille3.geometry}
        material={materials.Room_Transparent}
      />
      <mesh geometry={nodes.Cube011.geometry} material={materials.Room} />
      <mesh geometry={nodes.Around.geometry} material={materials.Room} />
      <mesh geometry={nodes.BaseMicro.geometry} material={materials.Room} />
      <mesh
        geometry={nodes.LiddleCylinder.geometry}
        material={materials.Room}
      />
      <mesh
        geometry={nodes.Mic.geometry}
        material={materials.Room}
        position={[3.1, 2.01, 0.86]}
        rotation={[0.24, -0.11, -0.72]}
      />
      <mesh
        geometry={nodes.Protect.geometry}
        material={materials.Room}
        position={[3.07, 2.04, 0.85]}
        rotation={[0.24, -0.11, -0.72]}
      />
      <mesh geometry={nodes.TurnButton.geometry} material={materials.Room} />
      <mesh geometry={nodes.Bouchon.geometry} material={materials.Room} />
      <mesh geometry={nodes.Bouteille.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cable001.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cable002.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cable003.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cable.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Room} />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials.Room}
        position={[0.61, 5.74, -4.01]}
      />
      <mesh geometry={nodes.Cube008.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder031.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder032.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder033.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder051.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials.Room} />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials.Room_Transparent}
      />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials.Room} />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={materials.Room_Transparent}
      />
      <mesh geometry={nodes.Cylinder013.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder014.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder015.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder016.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder017.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder034.geometry} material={materials.Room} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Room} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Room} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder028.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder029.geometry} material={materials.Room} />
      <mesh geometry={nodes.Plane016.geometry} material={materials.Room} />
      <mesh
        geometry={nodes.Cylinder019.geometry}
        material={materials.Room_Transparent}
      />
      <mesh geometry={nodes.Cylinder020.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder021.geometry} material={materials.Room} />
      <mesh geometry={nodes.PetitPied01.geometry} material={materials.Room} />
      <mesh geometry={nodes.PetitPied02.geometry} material={materials.Room} />
      <mesh geometry={nodes.Pied02.geometry} material={materials.Room} />
      <mesh geometry={nodes.Pied02001.geometry} material={materials.Room} />
      <mesh geometry={nodes.Table.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder053.geometry} material={materials.Room} />
      <mesh geometry={nodes.Plane008.geometry} material={materials.Room} />
      <mesh geometry={nodes.Plane009.geometry} material={materials.Focus} />
      <mesh geometry={nodes.Plane010.geometry} material={materials.Room} />
      <mesh geometry={nodes.Ecran.geometry} material={materials.Room} />
      <mesh geometry={nodes.PiedEcran.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder054.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder055.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder056.geometry} material={materials.Room} />
      <mesh geometry={nodes.Cylinder057.geometry} material={materials.Room} />
      <mesh geometry={nodes.Plane017.geometry} material={materials.Room} />
    </group>
  );
}

useGLTF.preload('/mesh/Desk/Desk.gltf');
